version: '3'
services:
  pixnet-frontend:
    image: ghcr.io/zlohbierdcul/pixnetworksite:main
    networks:
      - 'bridge'
    ports:
      - "80:3000"

  pixnet-backend:
    image: ghcr.io/zlohbierdcul/pixnetworksite_backend:main
    networks:
      - 'bridge'
    ports:
      - "3002:3002"

networks:
  bridge:
    driver: bridge